-- Create the users table if it does not exist.
create table if not exists public.app_users (
  id bigint generated by default as identity primary key,
  full_name text not null,
  email text not null unique,
  password_hash text not null,
  role text not null check (lower(role) in ('teacher', 'principal', 'accountant', 'student', 'library')),
  created_at timestamptz default now()
);

alter table public.app_users
  drop constraint if exists app_users_role_check;

update public.app_users
set role = lower(trim(role))
where role is not null;

update public.app_users
set role = 'library'
where lower(trim(role)) = 'library staff';

update public.app_users
set role = 'student'
where lower(trim(role)) not in ('teacher', 'principal', 'accountant', 'student', 'library');

alter table public.app_users
  add constraint app_users_role_check
  check (lower(role) in ('teacher', 'principal', 'accountant', 'student', 'library'));

-- Seed demo users.
-- For a real app, replace these plain values with password hashes.
insert into public.app_users (full_name, email, password_hash, role)
values
  ('Principal', 'principal@school.com', 'principal123', 'principal'),
  ('Teacher', 'teacher@school.com', 'teacher123', 'teacher'),
  ('Accountant', 'accountant@school.com', 'accountant123', 'accountant'),
  ('Student', 'student@school.com', 'student123', 'student'),
  ('Library Staff', 'library@school.com', 'library123', 'library')
on conflict (email) do nothing;

-- Create students table
create table if not exists public.students (
  id bigint generated by default as identity primary key,
  name text not null,
  grade text,
  status text,
  admission_date date,
  roll_number text,
  grades jsonb,
  avg_grade numeric,
  created_at timestamptz default now()
);

-- Create teachers table
create table if not exists public.teachers (
  id bigint generated by default as identity primary key,
  name text not null,
  subject text,
  status text,
  email text,
  created_at timestamptz default now()
);

-- Create fees table
create table if not exists public.fees (
  id bigint generated by default as identity primary key,
  student_id bigint references public.students(id) on delete set null,
  student text,
  fee numeric,
  status text,
  created_at timestamptz default now()
);

-- Create attendance summary table (class-level)
create table if not exists public.attendance (
  id bigint generated by default as identity primary key,
  class_name text,
  present integer,
  attendance numeric,
  created_at timestamptz default now()
);

-- Create student_attendance table (per-student)
create table if not exists public.student_attendance (
  id bigint generated by default as identity primary key,
  student_id bigint references public.students(id) on delete set null,
  student text,
  class_name text,
  status text,
  date date,
  created_at timestamptz default now()
);

-- Create teacher_attendance table
create table if not exists public.teacher_attendance (
  id bigint generated by default as identity primary key,
  teacher_id bigint references public.teachers(id) on delete set null,
  teacher text,
  date date,
  status text,
  created_at timestamptz default now()
);

-- Optional: create simple indexes to speed common lookups
create index if not exists idx_students_roll on public.students (roll_number);
create index if not exists idx_teachers_email on public.teachers (email);
create index if not exists idx_fees_student on public.fees (student_id);

